package rules.forward_chain;

import com.ftn.sbnz.model.models.Lake;
import com.ftn.sbnz.model.models.HydroelectricPowerPlant;
import com.ftn.sbnz.model.models.Turbine;
import com.ftn.sbnz.model.events.WaterDropValvesOpenEvent;
import com.ftn.sbnz.model.events.WaterLevelDecreasedEvent;
import com.ftn.sbnz.model.events.TurbinePressureDecreasedEvent;
import com.ftn.sbnz.model.events.ElectricityProductionDecreasedEvent;


rule "Water level above 80%"
    when
        $l: Lake(waterLvl > 80)
        not (WaterDropValvesOpenEvent($l.id == lakeId))
        $h: HydroelectricPowerPlant()
    then
        $h.setValvesOpened(true);
        insert(new WaterDropValvesOpenEvent($l.getId()));
        System.out.println("Water level above 80%. Valves will be opened.");
end

rule "Valves opened"
    when
        $w: WaterDropValvesOpenEvent()
        not (WaterLevelDecreasedEvent($w.lakeId == lakeId))
        $l: Lake()
    then
        modify($l){ setWaterLvl(35) }
        insert(new WaterLevelDecreasedEvent($l.getId()));
        System.out.println("Valves opened. Water level will be decreased.");
end

rule "Water level decreased"
    when
        $w: WaterLevelDecreasedEvent()
        $l: Lake(waterLvl < 40.0)
        not (TurbinePressureDecreasedEvent($l.id == lakeId))
        $h: HydroelectricPowerPlant()
    then
        for (Turbine turbine : $h.getTurbines()) {
            turbine.setPressure(turbine.getPressure() * 0.6);
        }
        insert(new TurbinePressureDecreasedEvent($l.getId()));
        System.out.println("Water level decreased. Pressure on turbines will be decreased.");
end

rule "Turbine pressure decreased"
    when
        $t: TurbinePressureDecreasedEvent()
        not ElectricityProductionDecreasedEvent($t.lakeId == lakeId)
        $h: HydroelectricPowerPlant()
    then
        $h.setElectricityProduction($h.getElectricityProduction() * 0.4);
        insert(new ElectricityProductionDecreasedEvent($t.getLakeId()));
        System.out.println("Pressure on turbines decreased. Electricity production will be decreased by 40%.");
end
